#
# Table structure for table 'tx_blsvspstbauantrag_domain_model_antragsanforderung'
#
CREATE TABLE tx_blsvspstbauantrag_domain_model_antragsanforderung (
	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,
  	feuser int(11) DEFAULT '0' NOT NULL,
	status int(11) DEFAULT '0' NOT NULL,
	art int(11) DEFAULT '0' NOT NULL,
	fall1 tinyint(1) unsigned DEFAULT '0' NOT NULL,
	fall2 tinyint(1) unsigned DEFAULT '0' NOT NULL,
	fall3 tinyint(1) unsigned DEFAULT '0' NOT NULL,
	vorzeitigerbaubeginn  tinyint(1) unsigned DEFAULT '0' NOT NULL,
	vereinsnummer int(11) DEFAULT '0' NOT NULL,
	vereinsname varchar(255) DEFAULT '' NOT NULL,
	blsvkreis int(11) DEFAULT '0' NOT NULL,
	stimmkreis int(11) DEFAULT '0' NOT NULL,
	ansprechpartnername varchar(255) DEFAULT '' NOT NULL,
	ansprechpartnervorname varchar(255) DEFAULT '' NOT NULL,
	ansprechpartnertitel int(11) DEFAULT '0' NOT NULL,
	ansprechpartnertelefondienst varchar(255) DEFAULT '' NOT NULL,
	ansprechpartnertelefonprivat varchar(255) DEFAULT '' NOT NULL,
	ansprechpartnermobil varchar(255) DEFAULT '' NOT NULL,
	ansprechpartnerfax varchar(255) DEFAULT '' NOT NULL,
	ansprechpartneremail varchar(255) DEFAULT '' NOT NULL,
	baugenehmigungspflichtig tinyint(1) unsigned DEFAULT '0' NOT NULL,
	massnahme1 varchar(255) DEFAULT '' NOT NULL,
	massnahmekosten1 int(11) DEFAULT '0' NOT NULL,
	massnahme2 varchar(255) DEFAULT '' NOT NULL,
	massnahmekosten2 int(11) DEFAULT '0' NOT NULL,
	massnahme3 varchar(255) DEFAULT '' NOT NULL,
	massnahmekosten3 int(11) DEFAULT '0' NOT NULL,
	massnahme4 varchar(255) DEFAULT '' NOT NULL,
	massnahmekosten4 int(11) DEFAULT '0' NOT NULL,
	massnahme5 varchar(255) DEFAULT '' NOT NULL,
	massnahmekosten5 int(11) DEFAULT '0' NOT NULL,
	barmittel int(11) DEFAULT '0' NOT NULL,
	eigeneleistungen int(11) DEFAULT '0' NOT NULL,
	unendgeltlichesachleistungen int(11) DEFAULT '0' NOT NULL,
	geldspenden int(11) DEFAULT '0' NOT NULL,
	zuschuesse int(11) DEFAULT '0' NOT NULL,
	fianzierungkommune int(11) DEFAULT '0' NOT NULL,
	finanzierunglkr int(11) DEFAULT '0' NOT NULL,
	finanzierungvorsteuer int(11) DEFAULT '0' NOT NULL,
	fremdgelder int(11) DEFAULT '0' NOT NULL,
	beantragtefoerderung int(11) DEFAULT '0' NOT NULL,
	begruendung text NOT NULL,
	bestehendesportstaetten33  text NOT NULL,
	stellungnahmetext  text NOT NULL,
	bestehendesportstaettentext  text NOT NULL,	
	
	erklaerung1 tinyint(1) unsigned DEFAULT '0' NOT NULL,
	erklaerung2 tinyint(1) unsigned DEFAULT '0' NOT NULL,
	begruendungablehnung text NOT NULL,
   begruendungannahme text NOT NULL,

	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	crdate int(11) unsigned DEFAULT '0' NOT NULL,
	cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	starttime int(11) unsigned DEFAULT '0' NOT NULL,
	endtime int(11) unsigned DEFAULT '0' NOT NULL,
	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(255) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage int(11) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
	t3ver_move_id int(11) DEFAULT '0' NOT NULL,
	sorting int(11) DEFAULT '0' NOT NULL,
	t3_origuid int(11) DEFAULT '0' NOT NULL,
	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumblob,
	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY t3ver_oid (t3ver_oid,t3ver_wsid),
	KEY language (l10n_parent,sys_language_uid)



);

#
# Table structure for table 'tx_blsvspstbauantrag_domain_model_regelantrag'
#


CREATE TABLE `tx_blsvspstbauantrag_domain_model_regelantrag` (
  `uid` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL DEFAULT '0',
  `vereinsnummer` int(11) NOT NULL DEFAULT '0',
  `blsvkreis` int(11) NOT NULL DEFAULT '0',
  `antragsnummer1` int(11) NOT NULL DEFAULT '0',
  `ansprechpartnernmae` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartnervorname` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartenertitel` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartnerteldienst` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartnertelprivat` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartner6mobil` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartneremail` varchar(255) NOT NULL DEFAULT '',
  `verwendungszweck1` varchar(255) NOT NULL DEFAULT '',
  `anzahl1` int(11) NOT NULL DEFAULT '0',
  `vbb1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil1` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck2` varchar(255) NOT NULL DEFAULT '',
  `anzahl2` int(11) NOT NULL DEFAULT '0',
  `vbb2` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil2` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck3` varchar(255) NOT NULL DEFAULT '',
  `anzahl3` int(11) NOT NULL DEFAULT '0',
  `vbb3` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil3` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck4` varchar(255) NOT NULL DEFAULT '',
  `anzahl4` int(11) NOT NULL DEFAULT '0',
  `vbb4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil4` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck5` varchar(255) NOT NULL DEFAULT '',
  `anzahl5` int(11) NOT NULL DEFAULT '0',
  `vbb5` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenenteil5` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck6` varchar(255) NOT NULL DEFAULT '',
  `anzahl6` int(11) NOT NULL DEFAULT '0',
  `vbb6` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil6` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck7` varchar(255) NOT NULL DEFAULT '',
  `anzahl7` int(11) NOT NULL DEFAULT '0',
  `vbb7` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil7` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck8` varchar(255) NOT NULL DEFAULT '',
  `anzahl8` int(11) NOT NULL DEFAULT '0',
  `vbb8` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil8` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck9` varchar(255) NOT NULL DEFAULT '',
  `anzahl9` int(11) NOT NULL DEFAULT '0',
  `vbb9` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil9` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck10` varchar(255) NOT NULL DEFAULT '',
  `anzahl10` int(11) NOT NULL DEFAULT '0',
  `vbb10` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil10` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck11` varchar(255) NOT NULL DEFAULT '',
  `anzahl11` int(11) NOT NULL DEFAULT '0',
  `vbb11` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil11` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck12` varchar(255) NOT NULL DEFAULT '',
  `anzahl12` int(11) NOT NULL DEFAULT '0',
  `vbb12` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil12` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck13` varchar(255) NOT NULL DEFAULT '',
  `anzahl13` int(11) NOT NULL DEFAULT '0',
  `vbb13` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil13` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck14` varchar(255) NOT NULL DEFAULT '',
  `anzahl14` int(11) NOT NULL DEFAULT '0',
  `vbb14` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil14` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck15` varchar(255) NOT NULL DEFAULT '',
  `anzahl15` int(11) NOT NULL DEFAULT '0',
  `vbb15` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil15` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck16` varchar(255) NOT NULL DEFAULT '',
  `anzahl16` int(11) NOT NULL DEFAULT '0',
  `vbb16` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil16` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck17` varchar(255) NOT NULL DEFAULT '',
  `anzahl17` int(11) NOT NULL DEFAULT '0',
  `vbb17` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil17` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck18` varchar(255) NOT NULL DEFAULT '',
  `anzahl18` int(11) NOT NULL DEFAULT '0',
  `vbb18` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil18` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck19` varchar(255) NOT NULL DEFAULT '',
  `anzahl19` int(11) NOT NULL DEFAULT '0',
  `vbb19` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil19` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck20` varchar(255) NOT NULL DEFAULT '',
  `anzahl20` int(11) NOT NULL DEFAULT '0',
  `vbb20` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil20` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck21` varchar(255) NOT NULL DEFAULT '',
  `anzahl21` int(11) NOT NULL DEFAULT '0',
  `vbb21` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil21` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck22` varchar(255) NOT NULL DEFAULT '',
  `anzahl22` int(11) NOT NULL DEFAULT '0',
  `vbb22` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil22` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck23` varchar(255) NOT NULL DEFAULT '',
  `anzahl23` int(11) NOT NULL DEFAULT '0',
  `vbb23` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil23` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck24` varchar(255) NOT NULL DEFAULT '',
  `anzahl24` int(11) NOT NULL DEFAULT '0',
  `vbb24` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil24` int(11) NOT NULL DEFAULT '0',
  `verwendungszweck25` varchar(255) NOT NULL DEFAULT '',
  `anzahl25` int(11) NOT NULL DEFAULT '0',
  `vbb25` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `kostenanteil25` int(11) NOT NULL DEFAULT '0',
  `finanzierung1` int(11) NOT NULL DEFAULT '0',
  `finanzierung2` int(11) NOT NULL DEFAULT '0',
  `fianzierung3` int(11) NOT NULL DEFAULT '0',
  `finanzierung4` int(11) NOT NULL DEFAULT '0',
  `finanzierung6` int(11) NOT NULL DEFAULT '0',
  `fianzierung7` int(11) NOT NULL DEFAULT '0',
  `finanzierung8` int(11) NOT NULL DEFAULT '0',
  `finanzierung9` int(11) NOT NULL DEFAULT '0',
  `finanzierung10` int(11) NOT NULL DEFAULT '0',
  `finanzierung11` int(11) NOT NULL DEFAULT '0',
  `finanzierung12` int(11) NOT NULL DEFAULT '0',
  `antragsnummer` int(11) unsigned DEFAULT '0',
  `tstamp` int(11) unsigned NOT NULL DEFAULT '0',
  `crdate` int(11) unsigned NOT NULL DEFAULT '0',
  `cruser_id` int(11) unsigned NOT NULL DEFAULT '0',
  `deleted` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `hidden` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `starttime` int(11) unsigned NOT NULL DEFAULT '0',
  `endtime` int(11) unsigned NOT NULL DEFAULT '0',
  `t3ver_oid` int(11) NOT NULL DEFAULT '0',
  `t3ver_id` int(11) NOT NULL DEFAULT '0',
  `t3ver_wsid` int(11) NOT NULL DEFAULT '0',
  `t3ver_label` varchar(255) NOT NULL DEFAULT '',
  `t3ver_state` tinyint(4) NOT NULL DEFAULT '0',
  `t3ver_stage` int(11) NOT NULL DEFAULT '0',
  `t3ver_count` int(11) NOT NULL DEFAULT '0',
  `t3ver_tstamp` int(11) NOT NULL DEFAULT '0',
  `t3ver_move_id` int(11) NOT NULL DEFAULT '0',
  `sorting` int(11) NOT NULL DEFAULT '0',
  `t3_origuid` int(11) NOT NULL DEFAULT '0',
  `sys_language_uid` int(11) NOT NULL DEFAULT '0',
  `l10n_parent` int(11) NOT NULL DEFAULT '0',
  `l10n_diffsource` mediumblob,
  `feuser` int(11) NOT NULL DEFAULT '0',
  `stimmkreis` int(11) NOT NULL DEFAULT '0',
  `ansprechpartnername` varchar(255) NOT NULL DEFAULT '',
  `ansprechpartnermobil` varchar(255) NOT NULL DEFAULT '',
  `finanzierungbarmittel` int(11) NOT NULL DEFAULT '0',
  `finanzierunggeldspenden` int(11) NOT NULL DEFAULT '0',
  `fianzierungkredit` int(11) NOT NULL DEFAULT '0',
  `finanzierungaleistung` int(11) NOT NULL DEFAULT '0',
  `finanzierungsachleistung` int(11) NOT NULL DEFAULT '0',
  `fianzierungkommune` int(11) NOT NULL DEFAULT '0',
  `finanzierunglkr` int(11) NOT NULL DEFAULT '0',
  `finanzierungsonstige` int(11) NOT NULL DEFAULT '0',
  `finanzierungvorsteuer` int(11) NOT NULL DEFAULT '0',
  `finanzierungzuschuss` int(11) NOT NULL DEFAULT '0',
  `finanzierungdarlehen` int(11) NOT NULL DEFAULT '0',
  `sicherunggrundschuld` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `sicherungkbuergschaft` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `sicherungbbuergschaft` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfkommune1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfkommune2` int(11) NOT NULL DEFAULT '0',
  `zwfkommune3` int(11) NOT NULL DEFAULT '0',
  `zwfkommune4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfkommune5` int(11) NOT NULL DEFAULT '0',
  `zwfkommune6` int(11) NOT NULL DEFAULT '0',
  `zwflandkreis1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwflandkreis2` int(11) NOT NULL DEFAULT '0',
  `zwflandkreis3` int(11) NOT NULL DEFAULT '0',
  `zwflandkreis4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwflandkreis5` int(11) NOT NULL DEFAULT '0',
  `zwflandkreis6` int(11) NOT NULL DEFAULT '0',
  `zwflandkreis7` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwflandkreis8` int(11) NOT NULL DEFAULT '0',
  `zwflandkreis9` int(11) NOT NULL DEFAULT '0',
  `zwfsonstige1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfsonstige2` int(11) NOT NULL DEFAULT '0',
  `zwfsonstige3` int(11) NOT NULL DEFAULT '0',
  `zwfsonstige4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfsonstige5` int(11) NOT NULL DEFAULT '0',
  `zwfsonstige6` int(11) NOT NULL DEFAULT '0',
  `zwfsonstige7` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfsonstige8` int(11) NOT NULL DEFAULT '0',
  `zwfsonstige9` int(11) NOT NULL DEFAULT '0',
  `zwfvorsteuer1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfvorsteuer2` int(11) NOT NULL DEFAULT '0',
  `zwfvorsteuer3` int(11) NOT NULL DEFAULT '0',
  `zwfvorsteuer4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfvorsteuer5` int(11) NOT NULL DEFAULT '0',
  `zwfvorsteuer6` int(11) NOT NULL DEFAULT '0',
  `zwfvorsteuer7` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfvorsteuer8` int(11) NOT NULL DEFAULT '0',
  `zwfvorsteuer9` int(11) NOT NULL DEFAULT '0',
  `zwfsmf1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfsmf2` int(11) NOT NULL DEFAULT '0',
  `zwfsmf3` int(11) NOT NULL DEFAULT '0',
  `zwfsmf4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfsmf5` int(11) NOT NULL DEFAULT '0',
  `zwfsmf6` int(11) NOT NULL DEFAULT '0',
  `zwfsmf7` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `zwfsmf8` int(11) NOT NULL DEFAULT '0',
  `zwfsmf9` int(11) NOT NULL DEFAULT '0',
  `jahreszahl1` int(11) NOT NULL DEFAULT '0',
  `jahreszahl2` int(11) NOT NULL DEFAULT '0',
  `guvdurchschnittsergebnis` int(11) NOT NULL DEFAULT '0',
  `vbbgruende1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vbbgruende2` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vbbgruende3` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vbbgruende4` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vbbgruende5` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `begruendungsonstige` text NOT NULL,
  `vbberklaerung1` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vbberklaerung2` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `vmlstichtag` int(11) NOT NULL DEFAULT '0',
  `anzahlboote` int(11) NOT NULL DEFAULT '0',
  `anzahlpferde` int(11) NOT NULL DEFAULT '0',
  `datumbauberatung` int(11) NOT NULL DEFAULT '0',
  `datumgespraechkv` int(11) NOT NULL DEFAULT '0',
  `ortsbesichtigungkv` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `absendedatum` int(11) NOT NULL DEFAULT '0',
  `eigentum` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erbbaurecht` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `pachtvertrag` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `eigentuemer` varchar(255) NOT NULL DEFAULT '',
  `grundstuecksgroesse` int(11) NOT NULL DEFAULT '0',
  `flurnummer` varchar(255) NOT NULL DEFAULT '',
  `gemarkung` varchar(255) NOT NULL DEFAULT '',
  `laufzeit` int(11) NOT NULL DEFAULT '0',
  `erklrechtsanspruch` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklmeldepflicht` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklbaubeginn` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklvollstaendigeangaben` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklsubvention` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklfinanzierung` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `masnahmenart` int(11) NOT NULL DEFAULT '0',
  `ansprechpartnerfax` varchar(255) NOT NULL DEFAULT '',
  `finanzierungzuschusskl` int(11) NOT NULL DEFAULT '0',
  `guvbeginn` int(11) NOT NULL DEFAULT '0',
  `guvende` int(11) NOT NULL DEFAULT '0',
  `guvbilanz` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `guveuerechnung` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `guveinnahmengesamt` int(11) NOT NULL DEFAULT '0',
  `einnahmenbeitraege` int(11) NOT NULL DEFAULT '0',
  `einnahmenspenden` int(11) NOT NULL DEFAULT '0',
  `einnahmenzuschuesse` int(11) NOT NULL DEFAULT '0',
  `guvausgabengesamt` int(11) NOT NULL DEFAULT '0',
  `ausgabeninstandhaltung` int(11) NOT NULL DEFAULT '0',
  `ausgabensportbetrieb` int(11) NOT NULL DEFAULT '0',
  `ausgabenverwaltung` int(11) NOT NULL DEFAULT '0',
  `ausgabenabschreibung` int(11) NOT NULL DEFAULT '0',
  `ueberschussfehlbetrag` int(11) NOT NULL DEFAULT '0',
  `vermoegensgegenstaende` int(11) NOT NULL DEFAULT '0',
  `sachanlagen` int(11) NOT NULL DEFAULT '0',
  `finanzanlagen` int(11) NOT NULL DEFAULT '0',
  `kassenbestand` int(11) NOT NULL DEFAULT '0',
  `bankguthaben` int(11) NOT NULL DEFAULT '0',
  `ruecklagenfrei` int(11) NOT NULL DEFAULT '0',
  `ruecklagenzweck` int(11) NOT NULL DEFAULT '0',
  `ruecklagenbetrieb` int(11) NOT NULL DEFAULT '0',
  `verbindlichkeitbank` int(11) NOT NULL DEFAULT '0',
  `verbindlichkeitblssmd` int(11) NOT NULL DEFAULT '0',
  `verbindlichkeitsonstige` int(11) NOT NULL DEFAULT '0',
  `jahreskapitaldienst` int(11) NOT NULL DEFAULT '0',
  `fachverbandmitglied1` int(11) NOT NULL DEFAULT '0',
  `mitglieder0110bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0110ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0111bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0111ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0112bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0112ueber26` int(11) NOT NULL DEFAULT '0',
  `fachverbandsmitglied2` int(11) NOT NULL DEFAULT '0',
  `mitglieder0210bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0210ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0211bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0211ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0212bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0212ueber26` int(11) NOT NULL DEFAULT '0',
  `fachverbandsmitglied3` int(11) NOT NULL DEFAULT '0',
  `mitglieder0310bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0310ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0311bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0311ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0312bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0312ueber26` int(11) NOT NULL DEFAULT '0',
  `fachverbandsmitglied4` int(11) NOT NULL DEFAULT '0',
  `mitglieder0410bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0410ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0411bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0411ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0412bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0412ueber26` int(11) NOT NULL DEFAULT '0',
  `fachverbandsmitglied5` int(11) NOT NULL DEFAULT '0',
  `mitglieder0510bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0510ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0511bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0511ueber26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0512bis26` int(11) NOT NULL DEFAULT '0',
  `mitglieder0512ueber26` int(11) NOT NULL DEFAULT '0',
  `fachverbandmannschaft1` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0110` int(11) NOT NULL DEFAULT '0',
  `erwachsene0110` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0111` int(11) NOT NULL DEFAULT '0',
  `erwachsene0111` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0112` int(11) NOT NULL DEFAULT '0',
  `erwachsene0112` int(11) NOT NULL DEFAULT '0',
  `fachverbandmannschaft2` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0210` int(11) NOT NULL DEFAULT '0',
  `erwachsene0210` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0211` int(11) NOT NULL DEFAULT '0',
  `erwachsene0211` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0212` int(11) NOT NULL DEFAULT '0',
  `erwachsene0212` int(11) NOT NULL DEFAULT '0',
  `fachverbandmannschaft3` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0310` int(11) NOT NULL DEFAULT '0',
  `erwachsene0310` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0311` int(11) NOT NULL DEFAULT '0',
  `erwachsene0311` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0312` int(11) NOT NULL DEFAULT '0',
  `erwachsene0312` int(11) NOT NULL DEFAULT '0',
  `fachverbandmannschaft4` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0410` int(11) NOT NULL DEFAULT '0',
  `erwachsene0410` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0411` int(11) NOT NULL DEFAULT '0',
  `erwachsene0411` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0412` int(11) NOT NULL DEFAULT '0',
  `erwachsene0412` int(11) NOT NULL DEFAULT '0',
  `fachverbandmannschaft5` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0510` int(11) NOT NULL DEFAULT '0',
  `erwachsene0510` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0511` int(11) NOT NULL DEFAULT '0',
  `erwachsene0511` int(11) NOT NULL DEFAULT '0',
  `schuelerjugend0512` int(11) NOT NULL DEFAULT '0',
  `erwachsene0512` int(11) NOT NULL DEFAULT '0',
  `fachverbandueleiter1` int(11) NOT NULL DEFAULT '0',
  `anzahl0110` int(11) NOT NULL DEFAULT '0',
  `anzahl0111` int(11) NOT NULL DEFAULT '0',
  `anzahl0112` int(11) NOT NULL DEFAULT '0',
  `fachverbandueleiter2` int(11) NOT NULL DEFAULT '0',
  `anzahl0210` int(11) NOT NULL DEFAULT '0',
  `anzahl0211` int(11) NOT NULL DEFAULT '0',
  `anzahl0212` int(11) NOT NULL DEFAULT '0',
  `fachverbandueleiter3` int(11) NOT NULL DEFAULT '0',
  `anzahl0310` int(11) NOT NULL DEFAULT '0',
  `anzahl0311` int(11) NOT NULL DEFAULT '0',
  `anzahl0312` int(11) NOT NULL DEFAULT '0',
  `fachverbandueleiter4` int(11) NOT NULL DEFAULT '0',
  `anzahl0410` int(11) NOT NULL DEFAULT '0',
  `anzahl0411` int(11) NOT NULL DEFAULT '0',
  `anzahl0412` int(11) NOT NULL DEFAULT '0',
  `fachverbandueleiter5` int(11) NOT NULL DEFAULT '0',
  `anzahl0510` int(11) NOT NULL DEFAULT '0',
  `anzahl0511` int(11) NOT NULL DEFAULT '0',
  `anzahl0512` int(11) NOT NULL DEFAULT '0',
  `fachverbandnutzung1` int(11) NOT NULL DEFAULT '0',
  `kinderjugendliche1` int(11) NOT NULL DEFAULT '0',
  `erwachsene1` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugw1` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugm1` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenw1` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenm1` int(11) NOT NULL DEFAULT '0',
  `lizensierteuel1` int(11) NOT NULL DEFAULT '0',
  `fachverbandnutzung2` int(11) NOT NULL DEFAULT '0',
  `kinderjugendliche2` int(11) NOT NULL DEFAULT '0',
  `erwachsene2` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugw2` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugm2` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenw2` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenm2` int(11) NOT NULL DEFAULT '0',
  `lizensierteuel2` int(11) NOT NULL DEFAULT '0',
  `fachverbandnutzung3` int(11) NOT NULL DEFAULT '0',
  `kinderjugendliche3` int(11) NOT NULL DEFAULT '0',
  `erwachsene3` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugw3` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugm3` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenw3` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenm3` int(11) NOT NULL DEFAULT '0',
  `lizensierteuel3` int(11) NOT NULL DEFAULT '0',
  `fachverbandnutzung4` int(11) NOT NULL DEFAULT '0',
  `kinderjugendliche4` int(11) NOT NULL DEFAULT '0',
  `erwachsene4` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugw4` int(11) NOT NULL DEFAULT '0',
  `mannschaftschuejugm4` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenw4` int(11) NOT NULL DEFAULT '0',
  `mannschafterwachsenm4` int(11) NOT NULL DEFAULT '0',
  `lizensierteuel4` int(11) NOT NULL DEFAULT '0',
  `notwendigkeitauslastung` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `notwendigkeitausrichtung` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `notwendigkeitbeduerfnis` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `notwendigkeitunterhalt` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `bauberatungja` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `bauberatungdatum` int(11) NOT NULL DEFAULT '0',
  `bauberatungnein` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `bestkenntnisnahme` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklnutzungdritte` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `erklkonzession` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `sonstiges_vermoegen` int(11) unsigned DEFAULT '0',
  `leistungen_dritter_gesamt` int(11) unsigned DEFAULT '0',
  `eigenbeteiligung_gesamt` int(11) unsigned DEFAULT '0',
  `gesamtkosten_brutto` int(11) unsigned DEFAULT '0',
  `egtvlaufzeit` varchar(255) NOT NULL DEFAULT '',
  `egtvgemarkung` varchar(255) NOT NULL DEFAULT '',
  `egtvflurnummer` varchar(255) NOT NULL DEFAULT '',
  `egtvgrundstuecksgroesse` varchar(255) NOT NULL DEFAULT '',
  `egtveigentuemer` varchar(255) NOT NULL DEFAULT '',
  `vereinsname` varchar(255) DEFAULT '',
  `bestehendesportstaetten1` int(11) DEFAULT '0',
  `bestehendesportstaetten11` int(11) DEFAULT '0',
  `bestehendesportstaetten111` int(11) DEFAULT '0',
  `bestehendesportstaetten1111` int(11) DEFAULT '0',
  `bestehendesportstaetten1112` int(11) DEFAULT '0',
  `bestehendesportstaetten12` int(11) DEFAULT '0',
  `bestehendesportstaetten21` int(11) DEFAULT '0',
  `bestehendesportstaetten211` int(11) DEFAULT '0',
  `bestehendesportstaetten212` int(11) DEFAULT '0',
  `bestehendesportstaetten22` int(11) DEFAULT '0',
  `bestehendesportstaetten221` int(11) DEFAULT '0',
  `bestehendesportstaetten222` int(11) DEFAULT '0',
  `bestehendesportstaetten3` int(11) DEFAULT '0',
  `bestehendesportstaetten31` int(11) DEFAULT '0',
  `bestehendesportstaetten32` int(11) DEFAULT '0',
  `bestehendesportstaetten4` int(11) DEFAULT '0',
  `bestehendesportstaetten41` int(11) DEFAULT '0',
  `bestehendesportstaetten42` int(11) DEFAULT '0',
  `bestehendesportstaetten51` int(11) DEFAULT '0',
  `bestehendesportstaetten511` int(11) DEFAULT '0',
  `bestehendesportstaetten512` int(11) DEFAULT '0',
  `bestehendesportstaetten521` int(11) DEFAULT '0',
  `bestehendesportstaetten522` int(11) DEFAULT '0',
  `bestehendesportstaetten531` int(11) DEFAULT '0',
  `bestehendesportstaetten532` int(11) DEFAULT '0',
  `finanzierung110` int(11) DEFAULT '0',
  `finanzierung111` int(11) DEFAULT '0',
  `finanzierung112` int(11) DEFAULT '0',
  `finanzierung121` int(11) DEFAULT '0',
  `finanzierung122` int(11) DEFAULT '0',
  `finanzierung131` int(11) DEFAULT '0',
  `finanzierung132` int(11) DEFAULT '0',
  `finanzierung141` int(11) DEFAULT '0',
  `finanzierung142` int(11) DEFAULT '0',
  `finanzierung21` int(11) DEFAULT '0',
  `finanzierung211` int(11) DEFAULT '0',
  `finanzierung212` int(11) DEFAULT '0',
  `finanzierung221` int(11) DEFAULT '0',
  `finanzierung222` int(11) DEFAULT '0',
  `finanzierung231` int(11) DEFAULT '0',
  `finanzierung232` int(11) DEFAULT '0',
  `finanzierung241` int(11) DEFAULT '0',
  `finanzierung242` int(11) DEFAULT '0',
  `finanzierung3` int(11) DEFAULT '0',
  `finanzierung31` int(11) DEFAULT '0',
  `finanzierung32` int(11) DEFAULT '0',
  `finanzierung40` int(11) DEFAULT '0',
  `finanzierung41` int(11) DEFAULT '0',
  `finanzierung42` int(11) DEFAULT '0',
  `finanzierung43` int(11) DEFAULT '0',
  `finanzierung44` int(11) DEFAULT '0',
  `finanzierung45` int(11) DEFAULT '0',
  `sonstiges1` int(11) DEFAULT '0',
  `sonstiges11` int(11) DEFAULT '0',
  `sonstiges2` int(11) DEFAULT '0',
  `sonstiges21` int(11) DEFAULT '0',
  `sonstiges22` int(11) DEFAULT '0',
  `sportlicheentwicklung1` int(11) DEFAULT '0',
  `sportlicheentwicklung11` int(11) DEFAULT '0',
  `sportlicheentwicklung12` int(11) DEFAULT '0',
  `sportlicheentwicklung13` int(11) DEFAULT '0',
  `sportlicheentwicklung2` int(11) DEFAULT '0',
  `sportlicheentwicklung21` int(11) DEFAULT '0',
  `sportlicheentwicklung211` int(11) DEFAULT '0',
  `sportlicheentwicklung2111` int(11) DEFAULT '0',
  `sportlicheentwicklung2112` int(11) DEFAULT '0',
  `sportlicheentwicklung2113` int(11) DEFAULT '0',
  `sportlicheentwicklung212` int(11) DEFAULT '0',
  `sportlicheentwicklung2121` int(11) DEFAULT '0',
  `sportlicheentwicklung2122` int(11) DEFAULT '0',
  `sportlicheentwicklung2123` int(11) DEFAULT '0',
  `sportlicheentwicklung213` int(11) DEFAULT '0',
  `sportlicheentwicklung2131` int(11) DEFAULT '0',
  `sportlicheentwicklung2132` int(11) DEFAULT '0',
  `sportlicheentwicklung2133` int(11) DEFAULT '0',
  `sportlicheentwicklung22` int(11) DEFAULT '0',
  `sportlicheentwicklung221` int(11) DEFAULT '0',
  `sportlicheentwicklung2211` int(11) DEFAULT '0',
  `sportlicheentwicklung2212` int(11) DEFAULT '0',
  `sportlicheentwicklung2213` int(11) DEFAULT '0',
  `sportlicheentwicklung222` int(11) DEFAULT '0',
  `sportlicheentwicklung2221` int(11) DEFAULT '0',
  `sportlicheentwicklung2222` int(11) DEFAULT '0',
  `sportlicheentwicklung2223` int(11) DEFAULT '0',
  `sportlicheentwicklung223` int(11) DEFAULT '0',
  `sportlicheentwicklung2231` int(11) DEFAULT '0',
  `sportlicheentwicklung2232` int(11) DEFAULT '0',
  `sportlicheentwicklung2233` int(11) DEFAULT '0',
  `sportlicheentwicklung23` int(11) DEFAULT '0',
  `sportlicheentwicklung231` int(11) DEFAULT '0',
  `sportlicheentwicklung2311` int(11) DEFAULT '0',
  `sportlicheentwicklung2312` int(11) DEFAULT '0',
  `sportlicheentwicklung2313` int(11) DEFAULT '0',
  `sportlicheentwicklung232` int(11) DEFAULT '0',
  `sportlicheentwicklung2321` int(11) DEFAULT '0',
  `sportlicheentwicklung2322` int(11) DEFAULT '0',
  `sportlicheentwicklung2323` int(11) DEFAULT '0',
  `sportlicheentwicklung233` int(11) DEFAULT '0',
  `sportlicheentwicklung2331` int(11) DEFAULT '0',
  `sportlicheentwicklung2332` int(11) DEFAULT '0',
  `sportlicheentwicklung2333` int(11) DEFAULT '0',
  `sportlicheentwicklung3` int(11) DEFAULT '0',
  `sportlicheentwicklung311` int(11) DEFAULT '0',
  `sportlicheentwicklung312` int(11) DEFAULT '0',
  `sportlicheentwicklung321` int(11) DEFAULT '0',
  `sportlicheentwicklung322` int(11) DEFAULT '0',
  `sportlicheentwicklung331` int(11) DEFAULT '0',
  `sportlicheentwicklung332` int(11) DEFAULT '0',
  `sportlicheentwicklung4` int(11) DEFAULT '0',
  `sportlicheentwicklung41` int(11) DEFAULT '0',
  `sportlicheentwicklung411` int(11) DEFAULT '0',
  `sportlicheentwicklung412` int(11) DEFAULT '0',
  `sportlicheentwicklung413` int(11) DEFAULT '0',
  `sportlicheentwicklung414` int(11) DEFAULT '0',
  `sportlicheentwicklung415` int(11) DEFAULT '0',
  `sportlicheentwicklung42` int(11) DEFAULT '0',
  `sportlicheentwicklung421` int(11) DEFAULT '0',
  `sportlicheentwicklung422` int(11) DEFAULT '0',
  `sportlicheentwicklung423` int(11) DEFAULT '0',
  `sportlicheentwicklung424` int(11) DEFAULT '0',
  `sportlicheentwicklung425` int(11) DEFAULT '0',
  `sportlicheentwicklung43` int(11) DEFAULT '0',
  `sportlicheentwicklung431` int(11) DEFAULT '0',
  `sportlicheentwicklung432` int(11) DEFAULT '0',
  `sportlicheentwicklung433` int(11) DEFAULT '0',
  `sportlicheentwicklung434` int(11) DEFAULT '0',
  `sportlicheentwicklung435` int(11) DEFAULT '0',
  `stellungnahme11` int(11) DEFAULT '0',
  `stellungnahme111` int(11) DEFAULT '0',
  `stellungnahme112` int(11) DEFAULT '0',
  `stellungnahme121` int(11) DEFAULT '0',
  `stellungnahme122` int(11) DEFAULT '0',
  `stellungnahme131` int(11) DEFAULT '0',
  `stellungnahme132` int(11) DEFAULT '0',
  `stellungnahme2` int(11) DEFAULT '0',
  `stellungnahme21` int(11) DEFAULT '0',
  `stellungnahme22` int(11) DEFAULT '0',
  `stellungnahme221` int(11) DEFAULT '0',
  `stellungnahme222` int(11) DEFAULT '0',
  `stellungnahme223` int(11) DEFAULT '0',
  `stellungnahme224` int(11) DEFAULT '0',
  `stellungnahme3` int(11) DEFAULT '0',
  `stellungnahme31` int(11) DEFAULT '0',
  `stellungnahme32` int(11) DEFAULT '0',
  `stellungnahme310` int(11) DEFAULT '0',
  `stellungnahme311` int(11) DEFAULT '0',
  `stellungnahme312` int(11) DEFAULT '0',
  `stellungnahme313` int(11) DEFAULT '0',
  `stellungnahme4` int(11) DEFAULT '0',
  `stellungnahme41` int(11) DEFAULT '0',
  `stellungnahme5` int(11) DEFAULT '0',
  `stellungnahme51` int(11) DEFAULT '0',
  `stellungnahme52` int(11) DEFAULT '0',
  `stellungnahme520` int(11) DEFAULT '0',
  `stellungnahme521` int(11) DEFAULT '0',
  `stellungnahme522` int(11) DEFAULT '0',
  `stellungnahme523` int(11) DEFAULT '0',
  `stellungnahme6` int(11) DEFAULT '0',
  `stellungnahme61` int(11) DEFAULT '0',
  `stellungnahme62` int(11) DEFAULT '0',
  `stellungnahme610` int(11) DEFAULT '0',
  `stellungnahme611` int(11) DEFAULT '0',
  `stellungnahme612` int(11) DEFAULT '0',
  `stellungnahme613` int(11) DEFAULT '0',
  `stellungnahme614` int(11) DEFAULT '0',
  `art` int(11) DEFAULT '0',
  `fall` int(11) DEFAULT '0',
  `hinweistext1` tinyint(4) DEFAULT '0',
  `hinweistext2` tinyint(4) DEFAULT '0',
  `hinweistext3` tinyint(4) DEFAULT '0',
  `hinweistext4` tinyint(4) DEFAULT '0',
  
  `kommunebank` int(11) DEFAULT '0',
  `kommuneprivat` int(11) DEFAULT '0',
  `landkreisbank` int(11) DEFAULT '0',
  `landkreiskommune` int(11) DEFAULT '0',
  `landkreisprivat` int(11) DEFAULT '0',
  `sonstigebank` int(11) DEFAULT '0',
  `sonstigekommune` int(11) DEFAULT '0',
  `sonstigeprivat` int(11) DEFAULT '0',
  `vorsteuererstbank` int(11) DEFAULT '0',
  `vorsteuererstkommune` int(11) DEFAULT '0',
  `vorsteuererstprivat` int(11) DEFAULT '0',
  `smfoerderungbank` int(11) DEFAULT '0',
  `smfoerderungkommune` int(11) DEFAULT '0',
  `smfoerderungprivat` int(11) DEFAULT '0',
  `kommunebetragbank` int(11) DEFAULT '0',
  `kommunebetragprivat` int(11) DEFAULT '0',
  `landkreisbetragbank` int(11) DEFAULT '0',
  `landkreisbetragkommune` int(11) DEFAULT '0',
  `landkreisbetragprivat` int(11) DEFAULT '0',
  `sonstigebetragbank` int(11) DEFAULT '0',
  `sonstigebetragkommune` int(11) DEFAULT '0',
  `sonstigebetragprivat` int(11) DEFAULT '0',
  `vorsteuererstbetragbank` int(11) DEFAULT '0',
  `vorsteuererstbetragkommune` int(11) DEFAULT '0',
  `vorsteuererstbetragprivat` int(11) DEFAULT '0',
  `smfoerderungbetragbank` int(11) DEFAULT '0',
  `smfoerderungbetragkommune` int(11) DEFAULT '0',
  `smfoerderungbetragprivat` int(11) DEFAULT '0',
  `betragsumme` int(11) DEFAULT '0',
  `kommunejbelastungbank` int(11) DEFAULT '0',
  `kommunejbelastungprivat` int(11) DEFAULT '0',
  `landkreisjbelastungbank` int(11) DEFAULT '0',
  `landkreisjbelastungkommune` int(11) DEFAULT '0',
  `landkreisjbelastungprivat` int(11) DEFAULT '0',
  `sonstigejbelastungbank` int(11) DEFAULT '0',
  `sonstigejbelastungkommune` int(11) DEFAULT '0',
  `sonstigejbelastungprivat` int(11) DEFAULT '0',
  `vorsteuererstjbelastungbank` int(11) DEFAULT '0',
  `vorsteuererstjbelastungkommune` int(11) DEFAULT '0',
  `vorsteuererstjbelastungprivat` int(11) DEFAULT '0',
  `smfoerderungjbelastungbank` int(11) DEFAULT '0',
  `smfoerderungjbelastungkommune` int(11) DEFAULT '0',
  `smfoerderungjbelastungprivat` int(11) DEFAULT '0',
  `jbelastungsumme` int(11) DEFAULT '0',
  `EARvon` int(11) DEFAULT '0',
  `EARbis` int(11) DEFAULT '0',
  `durchschnittsergebnis` int(11) DEFAULT '0',
  `wegfalloefffinanzmittel` int(11) DEFAULT '0',
  `fortbestandgefaehrdung` int(11) DEFAULT '0',
  `ersatzloserverlust` int(11) DEFAULT '0',
  `eintrittnachteiligerfolgen` int(11) DEFAULT '0',
  `notwendigkeitsonstige` int(11) DEFAULT '0',
  `notwendigkeitsonstigetextfeld` text NOT NULL,
  `vorzbaubeginnerkl1` int(11) DEFAULT '0',
  `vorzbaubeginnerkl2` int(11) DEFAULT '0',
  `b2vbb1` int(11) DEFAULT '0',
  `b2vbb2` int(11) DEFAULT '0',
  `b2vbb3` int(11) DEFAULT '0',
  `b2vbb4` int(11) DEFAULT '0',
  `b2vbb5` int(11) DEFAULT '0',
  `staatsmittelfoerderung1` int(11) DEFAULT '0',
  `staatsmittelfoerderung2` int(11) DEFAULT '0',
  `staatsmittelfoerderung3` int(11) DEFAULT '0',
  `staatsmittelfoerderung4` int(11) DEFAULT '0',
  `smfgs` int(11) DEFAULT '0',
  `smfkbs` int(11) DEFAULT '0',
  `smfbbs` int(11) DEFAULT '0',
  
  
  
  
  
  PRIMARY KEY (`uid`),
  KEY `parent` (`pid`),
  KEY `t3ver_oid` (`t3ver_oid`,`t3ver_wsid`),
  KEY `language` (`l10n_parent`,`sys_language_uid`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;



#
# Table structure for table 'tx_blsvspstbauantrag_domain_model_hilfetexte'
#
CREATE TABLE tx_blsvspstbauantrag_domain_model_hilfetexte (
	uid int(11) NOT NULL auto_increment,
	pid int(11) DEFAULT '0' NOT NULL,
	heading text NOT NULL,
	hilfekurz varchar(255) DEFAULT '' NOT NULL,
	hilfelang text NOT NULL,
	tstamp int(11) unsigned DEFAULT '0' NOT NULL,
	crdate int(11) unsigned DEFAULT '0' NOT NULL,
	cruser_id int(11) unsigned DEFAULT '0' NOT NULL,
	deleted tinyint(4) unsigned DEFAULT '0' NOT NULL,
	hidden tinyint(4) unsigned DEFAULT '0' NOT NULL,
	starttime int(11) unsigned DEFAULT '0' NOT NULL,
	endtime int(11) unsigned DEFAULT '0' NOT NULL,
	t3ver_oid int(11) DEFAULT '0' NOT NULL,
	t3ver_id int(11) DEFAULT '0' NOT NULL,
	t3ver_wsid int(11) DEFAULT '0' NOT NULL,
	t3ver_label varchar(255) DEFAULT '' NOT NULL,
	t3ver_state tinyint(4) DEFAULT '0' NOT NULL,
	t3ver_stage int(11) DEFAULT '0' NOT NULL,
	t3ver_count int(11) DEFAULT '0' NOT NULL,
	t3ver_tstamp int(11) DEFAULT '0' NOT NULL,
	t3ver_move_id int(11) DEFAULT '0' NOT NULL,
	sorting int(11) DEFAULT '0' NOT NULL,
	t3_origuid int(11) DEFAULT '0' NOT NULL,
	sys_language_uid int(11) DEFAULT '0' NOT NULL,
	l10n_parent int(11) DEFAULT '0' NOT NULL,
	l10n_diffsource mediumblob,
	PRIMARY KEY (uid),
	KEY parent (pid),
	KEY t3ver_oid (t3ver_oid,t3ver_wsid),
	KEY language (l10n_parent,sys_language_uid)

);